// import Positions from "../Positions"

export const Colors = {
  //------fixed color

  statusbarcolor: '#1F1F24',

  whiteColor: '#FFFFFF',
  black_color: '#000000',
  PlaceholderTextcolor: '#3a3a3a',
  BorderColor: '#454545',
  InputTextColor: '#E5E5EA',
  placeholder_color: '#d4d0d6',
  Placeholdercolor: '#A5A5A5',
  themeblack_color: '#1F1F24',
  HomeBackColor: '#28282E',
  text_color: '#737374',
  yellow_color: '#8E9F4E',
  text_color: '#3a3a3a',
  text_color2: '#454545',
  ModelColor: '#383840',
  ModelInsideButton: '#44444D',
  GreyButtonColor: '#898585',
  KYCBoxColor: '#39393D',
  CameraBoxColor: '#515159',
  cardbackground: '#F3F4F6',

  faltlistBorderHome: '#343439',
  green_type_color: '#0A966C',
  usdt_bg: '#313131',
  green_color: '#06A676',
  ButtonBarColor: '#E2FF6F',
  TermsColor: '#C7C7C8',
  GreyText: '#9FAFBB',
  YellowTextColor: '#E2FF6F',

  // -------Positions-------
  CartBackColor: '#2C2C34',
  PnlTextColor: '#9999A7',
  GreenText: '#00BD84',
  GreenButton: '#00BD84',
  RedButton: '#F24E53',
  OrangeColor: '#F46151',
  TogglebuttonBack: '#32333A',
  LoremColor: '#6B6B6E',
  GreyTextColor: '#676771',
  Yellow: '#E3A32A',

  // --------Order---------
  greyTextColor: '#787878',
  FooterBaclColor: '#222222',
  Pink: '#FED3CE',
  GreenWhite: '#F0FFF9',
  VerifieRed: '#FF636C',
  Green: '#29B57E',

  theme_color: '#309535',
  statusbar: '#1985ff',
  internetbackcolor: 'green',
  onlinebackcolor: 'green',
  internettextcolor: '#FFFFFF',
  onlinetextcolor: '#FFFFFF',
  mediabackground: '#FFFFFF',
  mediatextcolor: 'black',
  cancletextcolor: 'black',
  whiteColor: '#FFFFFF',
  white_color: '#FFFFFF',
  greyColor: 'gray',
  Otpresedcolor: 'green',
  otpcountcolor: 'red',
  otpverifycolor: '#1985ff',
  back_color: 'FFFFFF',
  border_color: '#efefee',
  text_color: '#3a3a3a',
  text_color2: '#454545',

  drawer_text_color: '#1E1E1E',

  explore_text_color: '#131313',
  res_time_color: '#B9B3B3',
  complete_color: '#88D594',
  imcomplete_color: '#C14F4F',
  textbackground_color: '#28282E',
  redColor: 'red',
  text_color3: '#5F5F60',

  //----developer color----------//
  // color for this app ---------------

  darkGreen_color: '#009640',
  darkGrey: '#575A57',
  inputBackground: '#FBFBFB',
  buttoncolor: '#309535',
  createColor: '#008C45',
  btnBorderGrey: '#E4E4E4',
  borderLine: '#B1B2B1',
  selectLanguageColor: '#1F231F',
  skipColor: '#797B79',
  otpColor: '#979797',
  offTintColor: '#A1ABB8',
  resend_otp_color: '#D64252',
  didnt_recieve_it_Color: '#6F6F6F',
  deactiveIndicator: '#F1F1F1',
  deactiveColor: '#2D3648',
  viewAllColor: '#797A7B',
  yellow_dark_color: '#FFCB0A',
  explore_color: '#725A01',
  title_color: '#323743',
  country_color: '#6C6C6B',

  modalTabColor: '#363939',
  tagbackColor: '#EFEFEF',
  borderGrey: '#DADADA',
  chatBack: '#CBD2E0',
  blockBorderColor: '#363936',
  profileColor: '#1F2223',
  logoutColor: '#D64252',
  faqBack: '#F0F7F1',
  timeBack: '#F7B23B',
  deleteColor: '#EA2A2A',
  transactionColor: '#717D96',
  closedColor: '#F8FAFB',
  subscriptionButtonColor: '#F4F4F4',
  ongoing_color: '#008C45',
  cancel_subscription: '#F06566',
  draftColor: '#0A6CFF',
  footerDeactive: '#969BA4',

  searchPlaceholderColor: '#B9B9B9',
  searchBorderColor: '#DCDCDC',
  tabTextColor: '#565D6D',
  proColor: '#D8EBD9',
  parisColor: '#494E58',
  hourAgoColor: '#969BA3',
  categoriesback: '#D7F2D9',
  lightYellow: '#FBE180',
  lightthemeColor: '#B2D8B4',
  unfilledColor: '#DDE0E4',
  listingColor: '#626978',
  imageContainerBorderColor: '#D7DADF',
  imagebackGroundColor: '#F3F3F5',
  promoBorderColor: '#C9CDD5',
  cartBorderColor: '#9095A1',
  containerBorderColor: '#E6E7EC',
  totalBackgroundColor: '#F8F9FA',
  shareWithSellerback: '#F3FBF4',
  chatbackgroundColor: '#F8F9FA',
  phoneNumber_Color: '#4A4F59',
  placeholderWalletColor: '#BDC1CA',

  walletquestionsColor: '#171A1F',
  reviewPersonColor: '#0A6CFF',
};

export const Font = {
  FontBlackLexend: 'LexendDeca-Black',
  FontBoldLexend: 'LexendDeca-Bold',
  FontExtraBoldLexend: 'LexendDeca-ExtraBold',
  FontExtraLightLexend: 'LexendDeca-ExtraLight',
  FontLightLexend: 'LexendDeca-Light',
  FontMediumLexend: 'LexendDeca-Medium',
  FontRegularLexend: 'LexendDeca-Regular',
  FontSemiBoldLexend: 'LexendDeca-SemiBold',
  FontThinLexend: 'LexendDeca-Thin',

  FontBoldManrope: 'Manrope-Bold',
  FontExtraBoldManrope: 'Manrope-ExtraBold',
  FontExtraLightManrope: 'Manrope-ExtraLight',
  FontLightManrope: 'Manrope-Light',
  FontMediumManrope: 'Manrope-Medium',
  FontRegularManrope: 'Manrope-Regular',
  FontSemiBoldManrope: 'Manrope-SemiBold',
};
