import {I18nManager} from 'react-native';
import {consolepro} from './Messageconsolevalidationprovider/Consoleprovider';
import {config} from './configProvider';
import {localStorage} from './localStorageProvider';
import RNRestart from 'react-native-restart';

global.language_key = 1;

export const language_get = async () => {
  var item = await localStorage.getItemObject('language');
  consolepro.consolelog('check launguage option', item);

  consolepro.consolelog('is rtl', I18nManager.isRTL);
  consolepro.consolelog('is rtl config', config.textalign);

  if (item != null) {
    consolepro.consolelog('language__1', config.language);
    config.language = item;
  }
  consolepro.consolelog('language_key123', config.language);
  if (item != null) {
    if (item == 0) {
      config.textalign = 'left';
      config.inverted = false;
    } else {
      config.textalign = 'right';
      config.inverted = true;
    }
  } else {
    I18nManager.forceRTL(false);
    I18nManager.allowRTL(false);
    config.textalign = 'left';
    config.inverted = false;
    localStorage.setItemObject('language', 0);
  }
};

export const language_set = async languagem => {
  consolepro.consolelog('I18nManager.isRTL Developer', I18nManager.isRTL);
  if (languagem != 1) {
    I18nManager.forceRTL(false);
    I18nManager.allowRTL(false);
    config.textalign = 'left';
    config.inverted = false;
    localStorage.setItemObject('language', 0);
    localStorage.removeItem('languagecathc');
    localStorage.removeItem('languagesetenglish');
    config.language = 0;
  } else {
    I18nManager.forceRTL(true);
    I18nManager.allowRTL(true);
    config.textalign = 'right';
    config.inverted = true;
    localStorage.setItemObject('language', 1);
    localStorage.setItemObject('languagecathc', 0);
    config.language = 1;
  }

  // setTimeout(() => {
  //   RNRestart.Restart();
  // }, 500);
};

export const Lang_chg = {
  // Media option ///////////////////
  MediaCamera: ['Choose Camera', ''],
  Mediagallery: ['Choose Gallery', ''],
  cancelmedia: ['Cancel', ''],

  //-----------not for developer use start ------------------//
  go_back_txt: ['Go back', 'Go back'],
  do_you_want_exit_txt: ['Do you want to exit app', 'Do you want to exit app'],
  do_you_want_goback_txt: ['Do you want to go back', 'Do you want to go back'],
  resend_txt: ['Resend', 'Resend'],
  OTP_txt: ['OTP', 'OTP'],
  Logout_txt: ['Logout', 'Logout'],
  are_you_logout: [
    'Are you sure , you want to logout?',
    'Are you sure , you want to logout?',
  ],
  notification_arr: ['Notification', 'Notification'],
  terms_and_condition_txt: ['Terms & Conditions', 'Terms and Conditions'],
  privacy_policy_txt: ['Privacy Policy', 'Privacy Policy'],
  about_us_txt: ['About Us', 'About Us'],
  delete_account_txt: ['Delete Account', 'حذف الحساب'],
  are_you_sure_delete_txt: ['Are you sure ?', 'هل انت متأكد من حذف الحساب؟'],
  content_not_found: ['Content Not Available', 'Content Not Available'],
  Contactus: ['Contact us', 'Contact Us'],
  Setting: ['Setting', 'Setting'],
  notification: ['notification', 'notification'],
  rate_app: ['Rate App', 'Rate App'],
  share_app: ['Share App', 'Share App'],
  Logout: ['Logout', 'Logout'],
  Show: ['Show', 'Show'],
  Hide: ['Hide', 'Hide'],

  //-----------notification start ---------//
  notifications_txt: ['Notifications'],
  clear_all: ['Clear all'],
  info: ['Information'],
  areyousure_txt: ['Are you sure , you want to clear notifications?'],
  //-----------notification end

  //-----------not for developer use end ------------------//

  log_in: ['Log In'],
  enter_registered_account_txt: [
    'Enter your registered account details for a personalised experience.',
  ],
  enterMail: ['Enter Email'],
  enter_password_txt: ['Enter Password'],
  or_txt: ['Or'],
  dont_have_an_acc: ['Don’t have an account? '],
  createAccount: ['Create Account'],
  arabic_txt: ['Arabic'],
  french_txt: ['French'],
  signup_txt: ['Sign Up'],
  orLoginWith: ['or Login with'],
  continuenwithgoogle_txt: ['Continue with Google'],
  continuenwithapple_txt: ['Continue with Apple'],
  contiueWithoutLogin: ['Continue without log In'],
  select_language: ['Select Language'],
  skip_txt: ['Skip'],
  get_started_txt: ['Get Started'],
  letsgetStarted: ['Let’s Get Started'],
  createAnAccount: ['Create an account to get started!'],
  name_txt: ['Name*'],
  EnterName: ['Enter Name'],
  mobile_txt: ['Mobile Number*'],
  EnterMobile: ['Enter Mobile Number'],
  confirm_password_txt: ['Confirm Password*'],
  enter_confirm_password_txt: ['Enter Confirm Password'],
  already_have_account: ['Already have an account? '],
  OtpVerification: ['OTP Verfication'],
  we_sent_an_email: [
    'We sent an email with a 6-digit code to your registered email. Please enter it so we can be sure that this email belongs to you.',
  ],
  verify_txt: ['Verify', 'Verify'],
  didnt_recieve_it_txt: ['Didn’t recieve the OTP? '],
  resend_otp_txt: ['Resend'],
  change_email: ['Change Email'],
  exitLang: ['Exit'],
  do_you_want_exit_txt: ['Do you want to exit app', 'Do you want to exit app'],
  forgot_password_txt: ['Forgot Password ?'],
  forgot_passwordTxt: ['Forgot Password'],
  send_txt: ['Send'],
  changepassword_txt: ['Change Password'],
  new_password_txt: ['New Password*'],
  enter_new_password_txt: ['Enter New Password'],
  confirm_new_password_txt: ['Confirm New Password*'],
  enter_confirm_new_password_txt: ['Enter Confirm New Password'],
  serach_txt: ['Search'],
  stories_txt: ['Stories'],
  view_all_txt: ['View more'],
  explore_txt: ['Explore'],
  categories_txt: ['Categories'],
  women_txt: ['Women'],
  shopNow_txt: ['Shop Now'],
  featured_txt: ['Featured'],
  inspired_by_searches: ['Inspired by your searches'],
  urgent_txt: ['Urgent'],
  popular_text: ['Popular'],
  near_by_txt: ['Nearby'],
  listing_txt: ['Listing'],
  stores_txt: ['Stores'],
  serach_for_a_store: ['Search for a store'],
  new_txt: ['New'],
  men_txt: ['Men'],
  women_txt: ['Women'],
  electronics_txt: ['Electronics'],
  car_txt: ['Car'],
  sort_txt: ['Sort'],
  details_txt: ['Details'],
  high_to_low_price: ['High to Low by Price'],
  low_to_low_high: ['Low to High by Price'],
  this_ad_is_from_professional: ['This ad is from Professional'],
  product_description: ['Product Description'],
  delivery_method: ['Delivery Method'],
  location_txt: ['Location'],
  follow_txt: ['Follow'],
  report_a_listing: ['Report a listing'],
  chat_txt: ['Chat'],
  inbox_txt: ['Inbox'],
  type_message_txt: ['Type Message...'],
  report_txt: ['Report'],
  block_txt: ['Block'],
  back_txt: ['Back'],
  are_you_sure_you_want_to_block: ['Are you sure you want to block the user?'],
  report_txt: ['Report', ''],
  reason_for_reporting: ['Reason for Reporting User'],
  message_txt: ['Message'],
  enter_message_txt: ['Enter Message'],
  profile_txt: ['Profile'],
  followers_txt: ['Followers'],
  following_txt: ['Following'],
  create_my_store: ['Create my store'],
  verifiy_my_identity: ['Verify my identity'],
  personal_information_txt: ['Personal Information'],
  wallet_txt: ['Wallet'],
  myListings_txt: ['My listings'],
  advertising_txt: ['Advertising (boosting)'],
  language_txt: ['Language'],
  help_and_support_txt: ['Help and support'],
  interact_with_application_txt: ['Interact with the application'],
  settings_and_inforamtion_txt: ['Settings and Information'],
  upload_profile_picture: ['Upload Profile Picture'],
  first_name_txt: ['First name'],
  first_name_asteric_txt: ['First name*'],
  last_name_txt: ['Last name'],
  last_name_asteric_txt: ['Last name*'],
  enter_first_name_txt: ['Enter first name'],
  enter_last_name_txt: ['Enter last name'],
  phone_number_txt: ['Phone number'],
  enter_phone_number_txt: ['Enter phone number'],
  place_of_residence_txt: ['Place of Residence'],
  enter_place_of_residence: ['Enter Place of Residence'],
  email_txt_1: ['Email'],
  email_txt: ['Email*'],
  password_txt: ['Password*'],
  yes_txt: ['Yes'],
  submit_txt: ['Submit'],
  Favourites_txt: ['Favorites'],
  male_txt: ['Male'],
  female_txt: ['Female'],
  gender_txt: ['Gender'],
  edit_txt: ['Edit'],
  products_txt: ['Products'],
  change_language: ['Change language'],
  faq_txt: ['FAQ'],
  live_chat_txt: ['Live chat'],
  notification_preference_txt: ['Notification Preferences'],
  legal_notice_txt: ['Legal Notices'],
  current_password_txt: ['Current Password*'],
  enter_current_password_txt: ['Enter Current Password'],
  reason_for_deleting: ['Reason for Deleting Account'],
  Log_out_txt: ['Log Out'],
  are_you_sure_you_want_to_logout: ['Are you sure you want to logout?'],
  message_asteric_txt: ['Message*'],
  get_in_touch: ['Get in touch'],
  we_are_here: ['We are here for you! How can we help?'],
  advertising_boosting_txt: ['Advertising Boosting'],
  advertising_options: ['Advertising Options'],
  extend_period_txt: ['Extend Period'],
  remaining_duration_txt: ['Remaining durations'],
  urgent_ad: ['Urgent Ad'],
  featured_ad: ['Featured Ad'],
  myListing_txt: ['My Listing'],
  filter_txt: ['Filter'],
  product_categories: ['Product Categories'],
  ratings_txt: ['Ratings'],
  apply_txt: ['Apply'],
  reset_all: ['Reset All'],
  mark_as_sold_txt: ['Mark as Sold'],
  pause_txt: ['Pause'],
  edit_txt: ['Edit'],
  delete_txt: ['Delete'],
  total_balance_txt: ['Total Balance'],
  transactions_txt: ['Transactions'],
  recharge_txt: ['Recharge'],
  transaction_id_txt: ['Transaction ID'],
  amount_txt: ['Amount'],
  enter_amount_txt: ['Enter Amount'],
  top_charge_txt: ['Top up Recharge'],
  instant_text: ['Instant'],
  are_you_sure_you_want_to_delete: [
    'Are you sure you want to Delete an account?',
  ],
  verification_process_txt: ['Verification Process'],
  upload_document_txt: ['Upload Document'],
  upload_selfie_txt: ['Upload Selfie'],
  store_txt: ['Store'],
  fashion_txt: ['Fashion'],
  open_now_txt: ['Open Now'],
  see_all_txt: ['See all'],
  total_products_txt: ['Total Products'],
  saved_txt: ['Saved'],
  upload_txt: ['Upload'],
  store_name_txt: ['Store Name'],
  enter_store_name_txt: ['Enter Store Name'],
  activity_description_txt: ['Activity Description'],
  enter_description_txt: ['Enter Description'],
  product_category_txt: ['Product Category'],
  select_category_txt: ['Select Category'],
  select_sub_category_txt: ['Select Sub Category'],
  product_sub_category_txt: ['Product Sub Category'],
  city_txt: ['City'],
  select_city_txt: ['Select City'],
  address_txt: ['Address'],
  enter_address_txt: ['Enter Address'],
  upload_store_photo_txt: ['Upload Store Photo'],
  upload_cover_photo_txt: ['Upload Cover Photo'],
  next_txt: ['Next'],
  availability_txt: ['Availability'],
  always_open_txt: ['Always Open'],
  from_txt: ['From'],
  to_txt: ['To'],
  create_store_txt: ['Create Store'],
  closed_txt: ['Closed'],
  monday_txt: ['Monday'],
  tuesday_txt: ['Tuesday'],
  wednesday_txt: ['Wednesday'],
  thursday_txt: ['Thursday'],
  friday_txt: ['Friday'],
  saturday_txt: ['Saturday'],
  sunday_txt: ['Sunday'],
  success_txt: ['Success!'],
  your_account_will_be_activate: [
    'Your account will be activated within 24 hours',
  ],
  ok_txt: ['Ok'],
  buySubscription_txt: ['Buy\nSubscription'],
  subscribe_txt: ['Subscribe'],
  myStore_txt: ['My Store'],
  store_profile_txt: ['Store Profile'],
  manage_my_store_txt: ['Manage My Store'],
  My_subscription_txt: ['Manage Subscription'],
  add_products_txt: ['Add Products'],
  subscription_history_txt: ['Subscription History'],
  cancel_subscription: ['Cancel Subscription'],
  buySubscription_btn_txt: ['Buy Subscription'],
  title_txt: ['Title'],
  enter_title_txt: ['Enter Title'],
  price_txt: ['Price'],
  enter_price_txt: ['Enter Price'],
  price_on_request_txt: ['Price on Request'],
  category_txt: ['Category'],
  sub_category_txt: ['Sub-Category'],
  save_as_draft_txt: ['Save as a draft'],
  choosing_correct_subCategory: [
    'Choosing the correct sub-category ensures your listing reaches the right audience.',
  ],
  choosing_correct_Category: [
    'Choosing the correct category ensures your listing reaches the right audience.',
  ],
  adjust_the_price_txt: [
    "Adjust the price based on the item's condition. Start with a reasonable price and be open to negotiation.",
  ],
  keep_it_concise_txt: [
    'Keep it concise and easy to read. Use keywords that buyers might search for.',
  ],
  take_clear_photos_txt: [
    'Take clear, well-lit photos that show your item from multiple angles.',
  ],
  add_photos_upto_20_txt: ['Add upto 20 photos'],
  product_condition_txt: ['Product condition'],
  provide_all_essentail_txt: [
    'Provide all essential details about your item, including flaws and features. Mention brand, model, size, and materials. Use clear language and bullet points for readability.',
  ],
  description_txt: ['Description'],
  delivery_info_txt: ['Delivery Info'],
  enter_delivery_info_txt: ['Enter Delivery Info'],
  clearly_state_your_preferred_txt: [
    'Clearly state your preferred delivery method and payment option',
  ],
  promotion_options_with_cost_txt: ['Promotion options with costs:'],
  add_more_photos_txt: ['Add more photos'],
  featured_for_24_txt: ['Featured for 24h'],
  featured_for_3_days_txt: ['Featured for 3 Days'],
  featured_for_7_days_txt: ['Featured for 7 Days'],
  confirm_and_continue_txt: ['Confirm and continue'],
  save_for_later_txt: ['Save for later and Buy credit'],
  edit_the_post_txt: ['Edit the post'],
  publish_my_listing_txt: ['Publish my listing'],
  listing_visibility_txt: ["Listing's Visibility"],
  promotion_txt: ['Promotion'],
  total_cost_txt: ['Total Cost'],
  expiration_date_of_promotion: ['Expiration date of promotion'],
  i_agree_to_the_terms_of_use_txt: [
    'I agree to the terms of use and certify that this listing complies with the platform rules.',
  ],
  congratulations_your_listing_txt: [
    'Congratulations! Your listing is now online.',
  ],
  view_listing_txt: ['View Listing'],
  back_to_home_txt: ['Back to home'],
  english_txt: ['English'],
  i_accept_txt: ['I accept'],
  and_txt: ['and'],

  // ------------------------------------
  hi_find_great_deals_txt: ['Hi! Find great deals here'],
  unsold_txt: ['Unsold'],
  continue_txt: ['Continue'],
  total_ads_txt: ['Total Ads'],
  remove_txt: ['Remove'],
  verifyYourIdentity: ['Verify your identity'],
  gointrust: ['Goin the trust of buyers and sellers'],
  benefitsOf: ['Benefits of identity verification'],
  strangth: ['Strengthen the trust of other users'],
  Increase_your: ['Increase your chances of selling faster'],
  Access_exclusive: ['Access exclusive features for verified accounts'],
  Documents_accepted: ['Documents accepted'],
  Nationidentity: ['National identity card'],
  Passport: ['Passport'],
  Residence_permit: ['Residence permit'],
  change_mobileNumber_txt: ['Change mobile number'],
  we_sent_a_code_txt: [
    'We sent a 6-digit code to your registered mobile number. Please enter it so we can be sure that this number belongs to you.',
  ],
  hi_what_are_you_looking_txt: ['Hi! whar are you looking for today?'],
  pro_txt: ['PRO'],
  learn_and_discover_txt: ['Learn and discover'],
  news_txt: ['News'],
  fashion_and_acc_txt: ['Fashion & accessories'],
  for_men_txt: ['For men'],
  high_tech_products_txt: ['High-tech products'],
  recent_listing_txt: ['Recent listing'],
  deliverAvailable_txt: ['Delivery is available'],
  product_condition_txt: ['Product condition'],
  verified_id_txt: ['Verified ID'],
  report_this_listing: ['Report this listing'],
  relevantProducts_txt: ['Relevant products'],
  see_all_txt: ['See all'],
  call_txt: ['Call'],
  add_to_cart_txt: ['Add to cart'],
  articles_txt: ['Articles'],
  find_a_store: ['Find a store'],
  all_chats_txt: ['All Chats'],
  sharedProducts_txt: ['Shared Product Chats'],
  review_txt: ['Review'],
  reviews_txt: ['Reviews'],
  rateNow_txt: ['Rate Now'],
  menu_txt: ['Menu'],
  viewProfile_txt: ['View Profile'],
  my_wallet_txt: ['My wallet'],
  myAds_txt: ['My ads'],
  myFavourite_listings_txt: ['My favourite listings'],
  myFavourite_sellers_txt: ['My favourite sellers'],
  myReviews_txt: ['My reviews'],
  cart_txt: ['Cart'],
  getinspired_txt: ['Get inspired'],
  createListing_txt: ['Create listing'],
  start_txt: ['Start'],
  chooseWhereTo_txt: ['Choose where to\npublish your listing'],
  youHaveTheOption_txt: [
    'You have the option of publishing the listing in your store or separately as a private individual',
  ],
  publishInMyStore_txt: ['Publish in my store'],
  listingWillbeVisisble_txt: ['Listing will be visible in your pro store'],
  publishAsPrivate_txt: ['Publish as a private individual'],
  lsitSeparatedFromStore_txt: ['Listing will be separated from your pro store'],
  selectTheRightCategory_txt: ['Select the right category'],
  selectTheRightSubCategory_txt: ['Select the right sub-category'],
  addUptoThree_txt: ['Add up to 3 photos'],
  continueForFree_txt: ['Continue for free with 3 photos'],
  addUptoTen_txt: ['Add up to 10 photos'],
  buyersLoveDetails_txt: ['Buyers love details. Show then more photos'],
  save_for_later_txt: ['Save for later'],
  choosing_right_delivery_option_txt: [
    'Choosing the right delivery option. If the buyer has to collect the item himself, choose “Delivery not available”',
  ],
  deliveryOptions_txt: ['Delivery options'],
  theSelectLocationFeature_txt: [
    'The "Select Location" feature empowers advertisers to precisely target their audience by selecting specific locations for their ads.',
  ],
  boostYourListing_txt: ['Boost your listing'],
  standOut_txt: ['Stand out from the crowd and sell faster!'],
  yourListingIsReady_txt: ['Your listing is ready!'],
  checkTheDetails_txt: [
    'Check the details and publish your listing in one click',
  ],
  youeCurrentBalance_txt: ['Your current balance'],
  byPostingListing_txt: [
    'By Posting this listing you agree to our terms of use and privacy Policy',
  ],
  publish_my_listing_txt: ['Publish my listing'],
  youeCreditWillCharge_txt: [
    'Your credit will be charged by this total amount.',
  ],
  totalToPay_txt: ['Total to pay'],
  doYouHavePromoCode_txt: ['Do you have a promo code?'],
  additionalPhotos_txt: ['Additional photos'],
  featureThreeDays_txt: ['Feature (3 days)'],
  listingCost_txt: ['Listing cost'],
  promoCode_txt: ['Promo code'],
  validate_txt: ['Validate'],
  olnyOnePromocodePerHour_txt: ['Only one promo code per order'],
  veryGoodCondition_txt: ['Very good condition'],
  goodCondition_txt: ['Good condition'],
  acceptTable_txt: ['Acceptable'],
  deliveryIsAvailable_txt: ['Delivery is available'],
  deliverynotAvailable_txt: ['Delivery is not available'],
  deliveryAvailable_txt: ['Delivery available'],
  yourCartIsEmpty_txt: ['Your cart is empty at the moment.'],
  addProductsToCart_txt: [
    'Add products to your cart to easily share them with professional sellers.',
  ],
  shareYourSelectionWithSeller_txt: [
    'Share your selection with sellers to streamline your purchase!',
  ],
  total_txt: ['Total'],
  shareWithSeller_txt: ['Share with seller'],
  cancelSharing_txt: ['Cancel sharing'],
  are_you_sure_you_want_to_stop_sharing: [
    'Are you sure you want to stop sharing this list?',
  ],
  cancel_txt: ['Cancel'],
  stopSharing_txt: ['Stop sharing'],
  blockUser_txt: ['Block user'],
  balance_txt: ['Balance'],
  transfer_txt: ['Transfer'],
  recharge_txt: ['Recharge'],
  transactions_txt: ['Transactions'],
  myPhoneNumber_txt: ['My phone number'],
  copyBpayCode_txt: ['Copy b-pay code'],
  openBankly_txt: ['Open bankily'],
  bankilyNumbet_txt: ['Bankily number'],
  paymentCode_txt: ['Payment code'],
  enterYourBankilyNumber_txt: ['Enter your bankily number'],
  enterAmountpaidOnBankily_txt: ['Enter amount you paid on bankily'],
  enterThecodeRecieved_txt: ['Enter the code you recieved from bankily'],
  recharge_txt: ['Recharge'],
  howDoIpayViabankily_txt: ['How do I pay via Bankily?'],
  needHelp_txt: ['Need help?'],
  boostMyListing_txt: ['Boost my listing'],
  viewPerformance_txt: ['View performance'],
  boostAd_txt: ['Boost Ad'],
  adPerformance_txt: ['Ad performance'],
  all_txt: ['All'],
  overAllkeys_txt: ['Overall Key Metrics'],
  genderBased_txt: ['Gender-based Metrics'],
  views_txt: ['Views'],
  totalNumberOfAdImp_txt: ['Total Number of ad impressions'],
  clicks_txt: ['Clicks'],
  totalNumberOfClicks_txt: ['Total number of clicks on the ad'],
  confirm_txt: ['Confirm'],
  professional_txt: ['Professional'],
  individualSeller_txt: ['Individual seller'],
  unfollow_txt: ['Unfollow'],
  customerReviews_txt: ['Customer reviews'],
  replyTo_txt: ['Reply to'],

  // ------piyush 20-09-24
  reply_txt: ['Reply'],
  createAnewAd_txt: ['Create a new ad'],
  boostSuccessOnChizein_txt: ['Boost your success on ChiZein'],
  promoteMyStore_txt: ['Promote my store'],
  promoteAListing_txt: ['Promote a listing'],
  attractMoreCustomers_txt: ['Attract more customers to all your products'],
  boostTheVisibility_txt: ['Boost the visibility of a specific product'],
  chooseYourPromotingStrategy_txt: [
    'Choose your promotion strategy and stand out from the crowd.',
  ],
  increaseMyVisisbility_txt: ['Increase your visibility and sales'],
  standOutFromTheCowd_txt: ['Stand out from the crowd and sell faster!'],
  chizein_txt: ['Chizein'],

  // yogesh sir ------------------->

  settings_and_inforamtion_txt: ['Settings & information'],
  notification_preference_txt: ['Notification preferences'],
  terms_and_condition_txt: ['Terms & conditions', 'Terms and conditions'],
  legal_notice_txt: ['Legal notices'],
  privacy_policy_txt: ['Privacy policy', 'Privacy policy'],
  about_us_txt: ['About us', 'About us'],
  changepassword_txt: ['Change password'],
  delete_account_txt: ['delete account', 'حذف الحساب'],
  Logout_txt: ['Log Out', 'Log Out'],
  Listing_Activity: ['Listing activity', 'Listing activity'],
  ChiZein_news: ['ChiZein news and updates', 'ChiZein news and updates'],
  Suspicious_logins: [
    'Suspicious logins or logins from a new device, important profile changes, critical security updates',
    'Suspicious logins or logins from a new device, important profile changes, critical security updates',
  ],
  Account_and_Security: ['Account and Security', 'Account and Security'],
  New_app_feature: [
    'New app features, community events and training, important platform information',
    'New app features, community events and training, important platform information',
  ],
  Payment_confirmations: [
    'Payment confirmations, subscription payment reminders',
    'Payment confirmations, subscription payment reminders',
  ],
  Transactions_and_payments: [
    'Transactions and payments',
    'Transactions and payments',
  ],
  Personalized_listing: [
    'Personalized listing suggestions, suggested shops to follow',
    'Personalized listing suggestions, suggested shops to follow',
  ],
  Recommendations_and_discoveries: [
    'Recommendations and discoveries',
    'Recommendations and discoveries',
  ],
  Promotions_and_special: [
    'Promotions and special offers',
    'Promotions and special offers',
  ],
  Promotions_on_subscription: [
    'Promotions on subscription costs, listing publications, or featured options',
    'Promotions on subscription costs, listing publications, or featured options',
  ],
  Followed_shops: ['Followed shops and sellers', 'Followed shops and sellers'],
  New_listings: [
    'New listings from followed shops and sellers',
    'New listings from followed shops and sellers',
  ],
  Comments_and_reviews: [
    'Comments and reviews on listings, listing performance, reminder for draft listings',
    'Comments and reviews on listings, listing performance, reminder for draft listings',
  ],
};
